// Section G — 4-Email Follow-Up Sequence
// Email 1 is the main pitch (generated by claudeService.generateWithMarcus).
// Emails 2-4 are follow-ups with escalating angles.

const { completeSmart, extractJsonObject } = require('./claudeService');

function formatNum(n) {
  if (!n) return '0';
  if (n >= 1000000) return `${(n / 1000000).toFixed(1)}M`;
  if (n >= 1000)    return `${Math.round(n / 1000)}K`;
  return String(Math.round(n));
}

// ── Email 2 — Make It Concrete (Section G.1) ──────────────────────────────────

async function generateFollowUp2(lead, email1, voiceDNA, intelligencePack) {
  const serviceType = voiceDNA.service || 'video editing';
  const senderName  = voiceDNA.name || 'Alex';
  const hook        = intelligencePack?.hook_data || {};

  // Map service type to what the free offer should be
  const freeOffer = {
    'video editing':          `a free 30-60 second sample edit of one of your existing videos`,
    'thumbnail design':       `1-2 free redesigned thumbnail mockups for a recent video`,
    'shorts editing':         `one sample Short cut from an existing video`,
    'scriptwriting':          `a rewritten hook/intro for your latest video`,
    'channel management':     `a quick audit of your channel operations with specific gaps`,
    'social media management':`a 7-day sample content calendar from your existing content`,
    'influencer marketing':   `a market rate breakdown for your subscriber count and niche`,
  };

  const offer = Object.entries(freeOffer).find(([k]) =>
    serviceType.toLowerCase().includes(k.toLowerCase())
  )?.[1] || `a quick sample of what I'd do for your specific format`;

  const prompt = `You are Marcus — writing follow-up email #2 in a sequence to a YouTube creator.

CONTEXT:
This is Email 2. The creator did not reply to Email 1.
Email 1 subject: "${email1?.subject || 'previous email'}"
Days since email 1: 3

THE CREATOR:
Channel: ${intelligencePack?.channel_name || lead.channel_name}
Subscribers: ${formatNum(intelligencePack?.subscribers || lead.subscriber_count)}
Niche: ${intelligencePack?.niche || lead.niche || 'general'}
Recent video: ${hook.most_recent_video_title || ((() => { try { return JSON.parse(lead.recent_videos || '[]')[0]?.title || 'N/A'; } catch { return 'N/A'; } })())}

SENDER:
Name: ${senderName}
Service: ${serviceType}
Voice: ${voiceDNA.communicationStyle || 'direct and conversational'}

ANGLE FOR EMAIL 2: Make It Concrete
Goal: Add ONE new thing that lowers the cost of saying yes.
New value to offer: ${offer}

RULES:
- 40-60 words body. Even shorter than Email 1.
- Jump straight to the new concrete value — brief callback to email 1 is ONE clause max
- NO: "just following up", "I wanted to circle back", "per my previous email", "checking in"
- CTA: even simpler than Email 1 (just reply yes/no)
- Match voice DNA: ${voiceDNA.communicationStyle || 'direct'}
- Apply all humanization rules — no AI tells, contractions throughout
- Sign: ${senderName} (first name only)

Return ONLY JSON:
{
  "subject": "<re: [original subject] OR new 3-5 word subject>",
  "body": "<email body, newlines as \\n>",
  "word_count": <number>
}`;

  try {
    const raw     = await completeSmart(prompt, '', 500);
    const cleaned = raw.replace(/```json|```/g, '').trim();
    const parsed  = JSON.parse(extractJsonObject(cleaned));
    return { subject: parsed.subject, body: parsed.body, sequence_position: 2, angle: 'make_it_concrete' };
  } catch (err) {
    console.error('[FollowUp] Email 2 generation failed:', err.message);
    return {
      subject: `re: ${email1?.subject || 'previous email'}`,
      body: `Wanted to add something concrete — happy to do ${offer} at no cost, so you can see the quality before deciding anything.\n\nWorth it?\n\n${senderName}`,
      sequence_position: 2,
      angle: 'make_it_concrete',
    };
  }
}

// ── Email 3 — Pure Value Drop (Section G.2) ───────────────────────────────────

async function generateFollowUp3(lead, email1, email2, voiceDNA, intelligencePack) {
  const serviceType = voiceDNA.service || 'video editing';
  const senderName  = voiceDNA.name || 'Alex';
  const hook        = intelligencePack?.hook_data || {};
  const niche       = intelligencePack?.niche || lead.niche || 'general';

  // Build a service-relevant value insight
  const valueInsightContext = {
    'video editing':    'editing technique or hook structure insight specific to their recent videos',
    'thumbnail design': 'specific CTR observation about their recent thumbnail choices',
    'shorts editing':   'specific moment in their recent video that would perform well as a Short',
    'scriptwriting':    'hook structure observation about their recent videos and what to test',
    'channel management': 'upload consistency or production workflow observation',
    'social media':     'content repurposing opportunity from their recent long-form videos',
  };

  const valueContext = Object.entries(valueInsightContext).find(([k]) =>
    serviceType.toLowerCase().includes(k.toLowerCase())
  )?.[1] || 'specific actionable insight about their channel performance';

  const prompt = `You are Marcus — writing follow-up email #3. This email has NO pitch, NO CTA, NO ask.
It is pure value — something genuinely useful whether or not they hire.

CONTEXT:
Creator did not reply to Emails 1 or 2.
Email 1 subject: "${email1?.subject || 'previous email'}"
Email 2 subject: "${email2?.subject || 'follow-up'}"

THE CREATOR:
Channel: ${intelligencePack?.channel_name || lead.channel_name}
Subscribers: ${formatNum(intelligencePack?.subscribers || lead.subscriber_count)}
Niche: ${niche}
Recent video: ${hook.most_recent_video_title || 'N/A'}
Recent avg views: ${formatNum(hook.recent_avg_views || lead.avg_views)}

SENDER:
Name: ${senderName}
Service: ${serviceType}
Voice: ${voiceDNA.communicationStyle || 'direct and conversational'}

THE VALUE TO GIVE: ${valueContext}

RULES — THIS EMAIL MUST FOLLOW ALL OF THESE:
- 50-70 words body
- Zero ask. Zero CTA. Zero service mention.
- Give one specific, actionable insight unique to their channel
- The insight should help them whether or not they hire
- End naturally — no CTA, no question, just a natural close
- Could end with something like "just something worth knowing" or nothing at all
- Sounds like genuine expertise, not a pitch
- No AI tells. Contractions throughout.
- Sign: ${senderName} (first name only)

Return ONLY JSON:
{
  "subject": "<NEW subject — not 're:' this time, 3-5 words lowercase>",
  "body": "<email body, newlines as \\n>",
  "word_count": <number>,
  "service_mentioned": false,
  "has_cta": false
}`;

  try {
    const raw     = await completeSmart(prompt, '', 500);
    const cleaned = raw.replace(/```json|```/g, '').trim();
    const parsed  = JSON.parse(extractJsonObject(cleaned));
    return { subject: parsed.subject, body: parsed.body, sequence_position: 3, angle: 'value_drop' };
  } catch (err) {
    console.error('[FollowUp] Email 3 generation failed:', err.message);
    return {
      subject: `something I noticed`,
      body: `Channels in the ${niche} space that push through plateaus almost always make one change: they front-load the payoff in the first 60 seconds instead of the setup.\n\nJust something worth testing on your next one.\n\n${senderName}`,
      sequence_position: 3,
      angle: 'value_drop',
    };
  }
}

// ── Email 4 — Graceful Exit (Section G.3 pattern + existing sequence wisdom) ──

async function generateFollowUp4(lead, email1, voiceDNA, intelligencePack) {
  const senderName = voiceDNA.name || 'Alex';
  const channelName = intelligencePack?.channel_name || lead.channel_name;

  const prompt = `You are Marcus — writing the final email in a 4-email sequence.

CONTEXT:
This is Email 4 — the last email. Creator has not replied to Emails 1, 2, or 3.
Email 1 subject: "${email1?.subject || 'previous email'}"

THE CREATOR:
Channel: ${channelName}
Recent video: ${intelligencePack?.hook_data?.most_recent_video_title || 'N/A'}

SENDER:
Name: ${senderName}
Voice: ${voiceDNA.communicationStyle || 'direct and conversational'}

ANGLE: Graceful Exit — The Closing Loop
The "I'm closing your file" email. People hate unresolved open loops.
This email gets replies because it removes the pressure permanently.

RULES:
- 25-40 words body only
- Zero pitch. Zero ask. Zero service mention.
- Close the loop gracefully — "closing your file for now"
- Leave the door genuinely open — "if timing changes, you know where to find me"
- Warm and zero pressure. No guilt. No fake urgency.
- Do NOT say "I'm sure you're busy" or any apologetic framing
- No AI tells. Contractions throughout.
- Sign: ${senderName} (first name only)

Return ONLY JSON:
{
  "subject": "<final subject, 3-5 words lowercase — something that signals closure>",
  "body": "<email body, newlines as \\n>",
  "word_count": <number>
}`;

  try {
    const raw     = await completeSmart(prompt, '', 300);
    const cleaned = raw.replace(/```json|```/g, '').trim();
    const parsed  = JSON.parse(extractJsonObject(cleaned));
    return { subject: parsed.subject, body: parsed.body, sequence_position: 4, angle: 'graceful_exit' };
  } catch (err) {
    console.error('[FollowUp] Email 4 generation failed:', err.message);
    return {
      subject: `closing the loop`,
      body: `Closing your file for now — don't want to keep cluttering your inbox.\n\nIf timing changes or you want to revisit, you know where to find me.\n\n${senderName}`,
      sequence_position: 4,
      angle: 'graceful_exit',
    };
  }
}

// ── Generate full 3-email follow-up sequence (emails 2-4) ─────────────────────

async function generateFollowUpSequence(lead, email1, voiceDNA, intelligencePack) {
  const results = [];

  try {
    const fu2 = await generateFollowUp2(lead, email1, voiceDNA, intelligencePack);
    results.push(fu2);
  } catch (err) {
    console.error('[FollowUp] Sequence email 2 failed:', err.message);
  }

  try {
    const fu3 = await generateFollowUp3(lead, email1, results[0], voiceDNA, intelligencePack);
    results.push(fu3);
  } catch (err) {
    console.error('[FollowUp] Sequence email 3 failed:', err.message);
  }

  try {
    const fu4 = await generateFollowUp4(lead, email1, voiceDNA, intelligencePack);
    results.push(fu4);
  } catch (err) {
    console.error('[FollowUp] Sequence email 4 failed:', err.message);
  }

  return results;
}

module.exports = {
  generateFollowUp2,
  generateFollowUp3,
  generateFollowUp4,
  generateFollowUpSequence,
};
